version: '3.8'

services:
  db:
    image: postgres:16
    container_name: mrp_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mrp
    ports:
      - "5332:5432"
    volumes:
      - mrp_data:/var/lib/postgresql/data

volumes:
  mrp_data:
